# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_SENSOR=n
CONFIG_BLINK=n
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_SPI_NOR=y
# Enable debug during sleep/stop/standby modes
CONFIG_STM32_ENABLE_DEBUG_SLEEP_STOP=y
CONFIG_GPIO=y
