# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

# -------------------- Common --------------------
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y
CONFIG_LOG=y

# Enable debug during sleep/stop/standby modes
CONFIG_STM32_ENABLE_DEBUG_SLEEP_STOP=y

# -------------------- Flash / QSPI partition (for FlashDB port) --------------------
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y

# -------------------- Modbus (official Zephyr subsystem) --------------------
CONFIG_DMA=y
CONFIG_DMA_STM32=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_LINE_CTRL=n
CONFIG_MODBUS=y
CONFIG_MODBUS_ROLE_SERVER=y
CONFIG_MODBUS_SERIAL=y
CONFIG_MODBUS_SERIAL_ASYNC_API=y

# Optional tuning
CONFIG_MAIN_STACK_SIZE=4096
