# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_SENSOR=n
CONFIG_BLINK=n
CONFIG_FLASH=y
# CONFIG_FLASH_PAGE_LAYOUT=y
# Enable debug during sleep/stop/standby modes
CONFIG_STM32_ENABLE_DEBUG_SLEEP_STOP=y
CONFIG_GPIO=y
# 必须开：异步串口总开关
CONFIG_UART_ASYNC_API=y

# 必须开：STM32 DMA 控制器
CONFIG_DMA=y
CONFIG_DMA_STM32=y

# 可选：开串口中断（必须）
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_NOCACHE_MEMORY=y

